### ISSUE TITLE
Implementing additional save button on bottom of page

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#58]
It would be more user friendly to add a save button on the bottom of any subpage which includes a table and the 'add row'  button. 
Because of positioning and color, one could intuitively be clicking on the 'add row' button instead of 'save'.
Another option for seperating would be giving the 'add row' button a different background color.

**Comment by dellermann** [comment]
Implemented in commit 2f5be29159b873b10896de1e56d0a42bf1f733ea.
