### ISSUE TITLE
Saving a new person will result in an error

### ISSUE THREAD

**Issue by philipdrozd** [dellermann/springcrm#59]
When trying to save a new person, one will encounter the error 'Bei der Verbindung zum LDAP-Server ldap1.corp.amc-world.de, Port 389 trat ein Fehler auf.' being redirected to the 'LDAP Problem' page eventually.

Additionally the LDAP settings subpage requires some work regarding responsiveness.

![ldap-error](https://cloud.githubusercontent.com/assets/13121869/8496711/a82b134e-2177-11e5-9f83-eb005c7a0f02.png)

![ldapsettingsresponsive](https://cloud.githubusercontent.com/assets/13121869/8496776/162a058a-2178-11e5-9f55-7e0895e196d2.png)

**Comment by dellermann** [comment]
The error is correct if no connection to the configured LDAP server could be established.  The LDAP settings page already has been redesigned.
